images:
  base_path: "/kaggle/working/tiny-imagenet-200/val"
  dir_ptrn: "images" 
  selection: "selection.txt"
model_name: "resnet50"
creator_name: "sloc"
creator_args:
  sloc:
    c_tv: 0.1
    c_magnitude: 0.01
results_path: "/kaggle/working/results"